language: node_js
node_js:
 - 4
 - 5
 - 6
 - 7
 - 8
 - node
script: make
deploy:
  provider: npm
  email: tatsy.mail@gmail.com
  api_key:
    secure: roTQgiuF6NYgvDDoo/jNxzSpCxLyaVuuAjfeMwFrOyeP9DWd41hBdAp5iiJYn/k1NxRMCFKU5ypnxXvkx/f8FQb/4J8ULKk6WCTxNy4Y/ta1wh/0v0auPDLl0I2iWDjjpR4WvMo//6R4dOsBLxmgnFhWFe6B+hn21E9Im/CNfD0=
  on:
    tags: true
    repo: tatsy/markdown-it-responsive
    all_branches: true
